// File: app/(tabs)/report.tsx
import { useLocalSearchParams, useRouter } from 'expo-router';
import React from 'react';
import { Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

type Scores = { clarity: number; assertiveness: number; empathy: number; structure: number };
type Report = {
  scores: Scores;
  summary: string;
  highlights: string[];
  improvements: string[];
  next_steps: string[];
  rationale?: string;
  what_went_well_desc?: string;
  what_to_improve_desc?: string;
  next_steps_desc?: string;
};

function Pill({ label, value }: { label: string; value: number }) {
  const pct = Math.max(0, Math.min(10, value)) * 10; // 0–100
  return (
    <View style={{ marginBottom: 12 }}>
      <Text style={{ fontWeight: '700', marginBottom: 6 }}>{label} — {value}/10</Text>
      <View style={{ height: 10, backgroundColor: '#e5e7eb', borderRadius: 999 }}>
        <View style={{ width: `${pct}%`, height: 10, backgroundColor: '#2563eb', borderRadius: 999 }} />
      </View>
    </View>
  );
}

function Card({
  title, bullets, bg, border, titleColor,
}:{
  title: string; bullets: string[]; bg: string; border: string; titleColor: string;
}) {
  return (
    <View style={{ width: '100%', backgroundColor: bg, borderColor: border, borderWidth: 1, borderRadius: 16, padding: 16 }}>
      <Text style={{ fontSize: 18, fontWeight: '800', color: titleColor }}>{title}</Text>
      {bullets?.length ? bullets.map((b, i) => (
        <Text key={i} style={{ marginTop: 6, color: '#111827' }}>• {b}</Text>
      )) : <Text style={{ marginTop: 6, color: '#6b7280' }}>No items</Text>}
    </View>
  );
}

function DescCard({ title, text, bg, border, titleColor }:{
  title: string; text?: string; bg: string; border: string; titleColor: string;
}) {
  if (!text?.trim()) return null;
  return (
    <View style={{ width: '100%', backgroundColor: bg, borderColor: border, borderWidth: 1, borderRadius: 16, padding: 16 }}>
      <Text style={{ fontSize: 18, fontWeight: '800', color: titleColor, marginBottom: 8 }}>{title}</Text>
      <Text style={{ color: '#111827', lineHeight: 20 }}>{text}</Text>
    </View>
  );
}

export default function ReportScreen() {
  const router = useRouter();
  const { report } = useLocalSearchParams<{ report?: string }>();

  let parsed: Report | null = null;
  try {
    if (report) parsed = JSON.parse(report);
  } catch {}

  const scores = parsed?.scores ?? { clarity: 5, assertiveness: 5, empathy: 5, structure: 5 };
  const summary = parsed?.summary ?? 'Summary unavailable.';
  const highlights = parsed?.highlights ?? [];
  const improvements = parsed?.improvements ?? [];
  const nextSteps = parsed?.next_steps ?? [];

  const rationale = parsed?.rationale ?? '';
  const wellDesc = parsed?.what_went_well_desc ?? '';
  const improveDesc = parsed?.what_to_improve_desc ?? '';
  const nextStepsDesc = parsed?.next_steps_desc ?? '';

  const goHome = () => router.push('/');

  return (
    <SafeAreaView style={{ flex: 1 }}>
      <ScrollView
        contentContainerStyle={{
          flexGrow: 1,
          alignItems: 'center',
          paddingHorizontal: 24,
          paddingVertical: 24,
        }}
        showsVerticalScrollIndicator
      >
        <View style={{ width: '100%', maxWidth: 520, gap: 16 }}>
          {/* Title */}
          <Text style={{ fontSize: 24, fontWeight: '800', textAlign: 'center' }}>
            Your Practice Report
          </Text>

          {/* Summary */}
          <View style={{ backgroundColor: '#f3f4f6', borderRadius: 12, padding: 12 }}>
            <Text style={{ textAlign: 'center', color: '#111827' }}>{summary}</Text>
          </View>

          {/* Scores */}
          <View style={{ backgroundColor: '#ffffff', borderRadius: 16, padding: 16, borderWidth: 1, borderColor: '#e5e7eb' }}>
            <Text style={{ fontSize: 18, fontWeight: '800', marginBottom: 12 }}>Scores</Text>
            <Pill label="Clarity" value={scores.clarity} />
            <Pill label="Assertiveness" value={scores.assertiveness} />
            <Pill label="Empathy" value={scores.empathy} />
            <Pill label="Structure" value={scores.structure} />
          </View>

          {/* NEW: Descriptive sections generated by LLM */}
          <DescCard title="Why these scores?" text={rationale} bg="#eef2ff" border="#c7d2fe" titleColor="#1e3a8a" />
          <DescCard title="What went well (details)" text={wellDesc} bg="#ecfdf5" border="#10b981" titleColor="#065f46" />
          <DescCard title="What to improve (details)" text={improveDesc} bg="#fff7ed" border="#fdba74" titleColor="#7c2d12" />
          <DescCard title="Next steps (details)" text={nextStepsDesc} bg="#e0f2fe" border="#3b82f6" titleColor="#1e3a8a" />

          {/* Bulleted sections (still helpful for skimming) */}
          <Card title="✅ What went well" bullets={highlights} bg="#ecfdf5" border="#10b981" titleColor="#065f46" />
          <Card title="⚙️ What to improve" bullets={improvements} bg="#fef3c7" border="#f59e0b" titleColor="#78350f" />
          <Card title="💡 Suggested next steps" bullets={nextSteps} bg="#e0f2fe" border="#3b82f6" titleColor="#1e3a8a" />

          {/* Back to Home */}
          <Pressable
            onPress={goHome}
            style={({ pressed }) => ({
              marginTop: 8,
              paddingVertical: 16,
              paddingHorizontal: 40,
              borderRadius: 30,
              backgroundColor: '#2563eb',
              opacity: pressed ? 0.9 : 1,
              alignItems: 'center',
              alignSelf: 'stretch',
            })}
          >
            <Text style={{ color: '#fff', fontWeight: '800', fontSize: 16 }}>
              Back to Home
            </Text>
          </Pressable>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}
